# Generated by Django 3.2 on 2021-04-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_auto_20210416_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='x_dim',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='y_dim',
            field=models.IntegerField(default=64),
            preserve_default=False,
        ),
    ]
