# Generated by Django 3.2 on 2021-04-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_auto_20210423_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='resolution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
