# Generated by Django 3.2 on 2021-07-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_map_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='dev_key',
            field=models.CharField(default='DEFAULT_DEVKEY', max_length=40),
            preserve_default=False,
        ),
    ]
